# Copyright IBM Corp. 2014, 2026
# SPDX-License-Identifier: MPL-2.0

name: 'Setup Ragel'
description: 'Install Ragel'

inputs:
  build_from_source:
    description: 'Whether to build Ragel from source'
    type: boolean
    default: false
  ref:
    description: 'Ref/version to build'
    type: string
    default: main

runs:
  using: "composite"
  steps:
    - name: Checkout Ragel source code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      if: ${{ inputs.build_from_source }}
      with:
        repository: adrian-thurston/colm-suite
        ref: ${{ inputs.ref }}
        path: ${{ runner.temp }}/ragel

    - name: Prepare Build Environment (macOS)
      shell: bash
      working-directory: ${{ runner.temp }}/ragel
      if: ${{ runner.os == 'macOS' }}
      run: brew install autoconf automake libtool

    - name: Prepare Build Environment (Windows)
      if: ${{ runner.os == 'Windows' && inputs.build_from_source }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        install: autoconf automake libtool pkg-config make gcc

    - name: Build Ragel (Linux)
      shell: bash
      working-directory: ${{ runner.temp }}/ragel
      if: ${{ runner.os == 'Linux' && inputs.build_from_source }}
      run: |
        ./autogen.sh
        ./configure
        make
        sudo make install
        sudo ldconfig

    - name: Build Ragel (macOS)
      shell: bash
      working-directory: ${{ runner.temp }}/ragel
      if: ${{ runner.os == 'macOS' && inputs.build_from_source }}
      run: |
        ./autogen.sh
        ./configure
        make
        sudo make install

    - name: Build Ragel (Windows)
      shell: msys2 {0}
      working-directory: ${{ runner.temp }}/ragel
      if: ${{ runner.os == 'Windows' && inputs.build_from_source }}
      run: |
        ./autogen.sh
        ./configure
        make
        make install

    - name: Install Ragel (Linux)
      shell: bash
      working-directory: ${{ runner.temp }}/ragel
      if: ${{ runner.os == 'Linux' && !inputs.build_from_source }}
      run: sudo apt install ragel

    - name: Install Ragel (macOS)
      shell: bash
      working-directory: ${{ runner.temp }}/ragel
      if: ${{ runner.os == 'macOS' && !inputs.build_from_source }}
      run: brew install ragel

    - name: Install Ragel (Windows)
      if: ${{ runner.os == 'Windows' && !inputs.build_from_source }}
      shell: pwsh
      working-directory: ${{ runner.temp }}/ragel
      run: winget install -e --accept-source-agreements --id PolarGoose.Ragel

    - name: Ragel version
      shell: ${{ case(runner.os == 'Windows', 'pwsh', 'bash') }}
      run: ragel --version
